export const Types = {
  GET_ALL_TOPICS: 'GET_ALL_TOPICS',
  GET_MY_TOPICS: 'GET_MY_TOPICS',
  TOPIC_DETAIL: 'TOPIC_DETAIL',
  ADD_TOPIC: 'ADD_TOPIC',
  UPDATE_TOPIC: 'UPDATE_TOPIC',
  DELETE_TOPIC: 'DELETE_TOPIC',
  ADD_COMMENT: 'ADD_COMMENT'
}
