export const Types = {
  GET_ALL_USERS: 'GET_ALL_USERS',
  ADD_USER: 'ADD_USER',
  UPLOAD_USERS: 'UPLOAD_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  GET_AUTH_USER: 'GET_AUTH_USER',
  GET_INITIAL_DATA: 'GET_INITIAL_DATA'
}
